//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centro_Medico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIAGNOSTICO
    {
        public int codigoDiag { get; set; }
        public int codigoCita { get; set; }
        public string nombreDiag { get; set; }
        public string tipoDiag { get; set; }
        public string Observaciones { get; set; }
        public string fotografias { get; set; }
        public string medicamentos { get; set; }
        public System.DateTime fechaEmision { get; set; }
    
        public virtual CITA CITA { get; set; }
    }
}
