//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centro_Medico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLEADO()
        {
            this.MEDICO = new HashSet<MEDICO>();
        }
    
        public int codigoEmp { get; set; }
        public int codigoTipEmp { get; set; }
        public string nombresEmp { get; set; }
        public string apPaternoEmp { get; set; }
        public string apMaternoEmp { get; set; }
        public string dpiEmp { get; set; }
        public string Colegiago { get; set; }
        public string sexoEmp { get; set; }
        public System.DateTime fechaNacimientoEmp { get; set; }
    
        public virtual TIPO_EMPLEADO TIPO_EMPLEADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEDICO> MEDICO { get; set; }
    }
}
